### ISSUE TITLE
SysTrayList fails to detect and display some of the tray system icons in Windows 11

### ISSUE THREAD

**Issue by k-kolev1985** [josephsl/systrayList#2]
### Discription
In Windows 11, the SysTrayList add-on fails to detect and display some of the system icons in the system tray. Such icons include, but may not be limited to, the following: Input Indicator, Network Indicator, System Volume Indicator, Clock.

### Steps to reproduce it
1. Launch NVDA.
2. Install the SysTrayList NVDA add-on.
3. Press NVDA+F11 to invoke the SysTrayList dialog with the list of available system tray icons.
4. Take note which icons appear in the list.
5. Dismiss the dialog.
6. Press Windows+B, to move the system focus to the system tray area.
7. Use the right arrow key to move towards the right of the list of visible icons in the system tray.
8. Take note which icons appear in this list and compare with step 4.

### Expected results
SysTrayList should show in its list all of the available icons/buttons in the system tray area.

### Actual results
SysTrayList does not show in its list some system icons like Network, Sound Volume, Clock, etc.

### Test environment:
- Operating system: Windows 11 Pro version 21H2 (build 22000.282), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-24184,fd9ae8c4, installed, in bulgarian.
- SysTrayList add-on version: 21.06.
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

**Comment by ruifontes** [comment]
Fixed on 2023.03
